<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">

  <xsl:output method="html" indent="yes" encoding="UTF-8"/>

  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>Sitemap — Mullaways Medical Cannabis</title>
        <style>
          *{margin:0;padding:0;box-sizing:border-box}
          body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;background:#0a0a0a;color:#e0e0e0;padding:2rem;max-width:1200px;margin:0 auto}
          h1{font-size:1.6rem;margin-bottom:.25rem;color:#4ade80}
          .meta{color:#888;font-size:.85rem;margin-bottom:1.5rem}
          table{width:100%;border-collapse:collapse;font-size:.9rem}
          thead th{text-align:left;padding:.6rem .8rem;background:#1a1a1a;color:#aaa;font-weight:600;border-bottom:1px solid #333;position:sticky;top:0}
          tbody tr{border-bottom:1px solid #1a1a1a}
          tbody tr:hover{background:#111}
          td{padding:.55rem .8rem}
          a{color:#4ade80;text-decoration:none;word-break:break-all}
          a:hover{text-decoration:underline;color:#86efac}
          .badge{display:inline-block;padding:.15rem .45rem;border-radius:4px;font-size:.75rem;font-weight:600;background:#1a2e1a;color:#4ade80}
          .priority{text-align:center}
          .num{text-align:right;color:#666;font-variant-numeric:tabular-nums}
          footer{margin-top:2rem;text-align:center;color:#555;font-size:.8rem}
        </style>
      </head>
      <body>
        <h1>XML Sitemap</h1>
        <p class="meta">
          This sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.
        </p>

        <table>
          <thead>
            <tr>
              <th style="width:3rem">#</th>
              <th>URL</th>
              <th style="width:7rem">Priority</th>
              <th style="width:7rem">Change Freq</th>
              <th style="width:11rem">Last Modified</th>
            </tr>
          </thead>
          <tbody>
            <xsl:for-each select="sitemap:urlset/sitemap:url">
              <tr>
                <td class="num"><xsl:value-of select="position()"/></td>
                <td>
                  <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                </td>
                <td class="priority">
                  <span class="badge"><xsl:value-of select="sitemap:priority"/></span>
                </td>
                <td><xsl:value-of select="sitemap:changefreq"/></td>
                <td><xsl:value-of select="substring(sitemap:lastmod, 1, 10)"/></td>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>

        <footer>
          Generated by @astrojs/sitemap
        </footer>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
